steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/live-agent-ui', '.']
  dir: 'client'

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/live-agent-ui']

images:
- 'gcr.io/$PROJECT_ID/live-agent-ui'