
VAIS_DATASTORE_ID = "VAIS_DATASTORE_ID"
VAIS_DATASTORE_REGION="global"

GCP_PROJECT_ID = "GCP_PROJECT_ID"
GCP_LOCATION = "GCP_LOCATION"
GCS_BUCKET_NAME = "GCS_BUCKET_NAME"

PG_INSTANCE_NAME="PG_INSTANCE_NAME"
PG_DATABASE_NAME="PG_DATABASE_NAME"
PG_DATABASE_USER="PG_DATABASE_USER"
PG_DATABASE_PASSWORD="PG_DATABASE_PASSWORD"
PG_TABLE_NAME="PG_TABLE_NAME"
PG_HOST="PG_HOST"
PG_PORT="PG_PORT"
PG_DRIVER="PG_DRIVER" #"pymysql",#"pg8000","psycopg2",
PG_COLLECTION="PG_COLLECTION"

VAIS_DATASTORE_ID = "VAIS_DATASTORE_ID"
VAIS_DATASTORE_REGION="VAIS_DATASTORE_REGION"