from utils import consts

GCP_PROJECT_ID = ""
GCP_LOCATION = ""
INPUT_BUCKET = ""
FILE_TYPE=consts.DocType.HTML.value

PG_INSTANCE_NAME=""
PG_DATABASE_NAME=""
PG_HOST=""
PG_PORT="5432"
PG_DATABASE_USER=""
PG_DATABASE_PASSWORD=""
PG_TABLE_NAME=""
PG_COLLECTION_NAME=""
PG_DRIVER="psycopg2"