DATA_LOCAL_PATH = ""

GCP_PROJECT_ID = ""
GCP_LOCATION = ""
GCS_BUCKET_NAME = ""

PG_INSTANCE_NAME=""
PG_DATABASE_NAME=""
PG_HOST=""
PG_PORT=""
PG_DATABASE_USER=""
PG_DATABASE_PASSWORD=""
PG_TABLE_NAME=""
PG_COLLECTION_NAME=""
